Concrete implementation of Semantic Search
theam/eLLMental-kt pull request #12
Opened 2023-07-05 13:34 UTC by NickSeagull

2023-07-07 16:41 UTC, mnlx approved these changes
LGTM! 

The tests look nice :1st_place_medal: !

2023-07-10 09:19 UTC, adrian-lorenzo requested changes
This is an awesome implementation, but I'm not convinced about certain parts. Let's discuss them!

2023-07-10 09:19 UTC, adrian-lorenzo commented on llmental-core/src/main/kotlin/com/theagilemonkeys/llmental/core/api/HTTP.kt
> +                val message = expectedException.message ?: "Unknown error"
I think we should create a constant from `Unknown error`, since this is going to be widely used.

2023-07-10 09:19 UTC, adrian-lorenzo commented on llmental-core/src/main/kotlin/com/theagilemonkeys/llmental/core/schema/SemanticEntry.kt
> -    val clusterId: Id? = null,
If we remove the `clusterId` we will have problems in our implemented use cases.
We are treating the whole abstraction as a single index. Still, in reality, in many use cases, we need dynamic clusters to search specific entries depending on use case conditions (e.g. A user should search only in their own documents). 

Take into account that if we remove this, part of our team won't be able to use this tool.

2023-07-10 09:19 UTC, adrian-lorenzo commented on modules/embeddings-model/src/main/kotlin/com/theagilemonkeys/llmental/embeddingsModel/openai/OpenAIEmbeddingsModel.kt
> +            model = ModelId("text-embedding-ada-002"),
I believe model ID should be an environment variable, something configurable by the user.

2023-07-10 09:19 UTC, adrian-lorenzo commented on modules/semantic-search/src/main/kotlin/com/theagilemonkeys/llmental/semanticsearch/SemanticSearch.kt
>      }
I think the baseline implementation should expect a list of texts.

In our open-source implementations, if you want to take full advantage of your model capabilities, you need to send as many text chunks as possible so you can take advantage of your GPU's full parallelization capabilities.

OpenAI and other providers might not have this problem because they are probably parallelizing with request pools, but we are not allowed to do this in non-SaaS implementations.

I think that this service should abstract this part. If you are using your own embedding model, you have a mechanism to take advantage of parallelization (the list of strings) and then in your own implementation, you can send requests in batches. And the same goes with providers like OpenAI (the batch size would be 1)

2023-07-11 16:11 UTC, NickSeagull commented on llmental-core/src/main/kotlin/com/theagilemonkeys/llmental/core/schema/SemanticEntry.kt
> -    val clusterId: Id? = null,
Had no idea about this, I thought it was an alternative name for `id`, gonna put it back again!

2023-07-11 16:13 UTC, NickSeagull commented on modules/embeddings-model/src/main/kotlin/com/theagilemonkeys/llmental/embeddingsModel/openai/OpenAIEmbeddingsModel.kt
> +            model = ModelId("text-embedding-ada-002"),
I believe that this should be addressed by the plugin system. Let's not introduce a new way of configuring services until then IMO.

2023-07-11 16:48 UTC, NickSeagull commented
@adrian-lorenzo changes applied

2023-07-12 15:44 UTC, javiertoledo approved these changes
LGTM, let's put that string in a constant though

2023-07-12 15:44 UTC, javiertoledo commented on modules/embeddings-model/src/main/kotlin/com/theagilemonkeys/llmental/embeddingsModel/openai/OpenAIEmbeddingsModel.kt
> +            model = ModelId("text-embedding-ada-002"),
Yeah, let's at least put it in a constants file or a constant at the beginning of the file 😜

2023-07-12 16:19 UTC, merged