Added documentation deployment for major cloud providers
theam/eLLMental-kt pull request #13
Opened 2023-07-05 21:28 UTC by mnlx

2023-07-07 15:50 UTC, NickSeagull approved these changes
Awesome! Could you remove the `<br>`s please? They can interfere in the rendering process if we decide to move the docs to another platform :)

2023-07-07 15:50 UTC, NickSeagull commented on README.md
> +<br>
I think that for the better we can either remove this or add a horizontal separator `---`

```suggestion
```

2023-07-07 15:50 UTC, NickSeagull commented on README.md
> +
```suggestion
```

2023-07-08 00:59 UTC, mnlx commented on README.md
> +<br>
Done!

2023-07-10 09:08 UTC, adrian-lorenzo requested changes
To be honest, I believe that the example project should be in another repository.

1. It would make it very easy to just clone and use.
2. We would keep things simple and small.

What do you think? @javiertoledo @NickSeagull @mnlx @juanjoman

2023-07-10 09:11 UTC, javiertoledo commented
@adrian-lorenzo I think we should remove it in a couple of iterations, but for now, I'd keep it here.

2023-07-10 13:27 UTC, mnlx commented
I agree with Javi and we should also wait for our decision of the ideal developer experience before we make any bigger changes.

2023-07-13 09:25 UTC, juanjoman approved these changes

2023-07-13 14:50 UTC, juanjoman commented
I'm moving this to our new docs repo @mnlx https://github.com/theam/ellmental-docs/pull/1

2023-07-13 14:50 UTC, closed without merging