Llm 85/add readme
theam/eLLMental-kt pull request #14
Opened 2023-07-06 14:20 UTC by juanjoman

https://agilemonkeys.atlassian.net/browse/LLM-85
https://agilemonkeys.atlassian.net/browse/LLM-160

2023-07-07 15:48 UTC, NickSeagull approved these changes
Looking great! Let's pass this through ChatGPT or Grammarly to ensure that there are no typos or weird expressions

2023-07-07 15:48 UTC, NickSeagull commented on README.md
> +5. **Flexibility:** Application's needs grow constantly, and so does AI applications. That's why we are adopting a
```suggestion
5. **Flexibility:** Regular applications need to grow constantly, and so do AI applications. That's why we are adopting a
```

2023-07-07 15:48 UTC, NickSeagull commented on README.md
> +AI applications. This API currently support two kind of operations: write (HTTP POST), and read (HTTP GET). You can provide
```suggestion
AI applications. This API currently support two kind of operations: write, and read. These two kinds of operations can be easily mapped to any kind of API protocol. By default we offer a REST-style HTTP mapping, but you can easily map it to GraphQL or gRPC. It is easy to make
```

2023-07-07 15:48 UTC, NickSeagull commented on README.md
> +| JVM Version          | 17     |
I think that we can remove this, and just add a phrase in the first paragraph saying that this is a Kotlin library.

2023-07-07 15:48 UTC, NickSeagull commented on README.md
> +modules and components.
I'd remove this part for now

2023-07-07 17:13 UTC, mnlx approved these changes
Nice job! You shouldn't wait on my work, I'll add it once it's done.

2023-07-10 08:58 UTC, adrian-lorenzo requested changes
Great work! 

I think this needs further iteration, but we are in a good direction!

2023-07-10 08:58 UTC, adrian-lorenzo commented on README.md
> +5. **Flexibility:** Application's needs grow constantly, and so does AI applications. That's why we are adopting a
I want to review this part with Chechu @juanjoman. I'm not convinced about the content. The pitch is not right enough.

2023-07-10 08:58 UTC, adrian-lorenzo commented on README.md
> +# Getting started
Getting started should include the following stuff (mostly on the documentation site):

1. Guide to creating a semantic index easily
2. Guide to creating your own module

Both of them should be short and direct, in my opinion. We are missing this.

2023-07-10 08:58 UTC, adrian-lorenzo commented on README.md
> +modules and components.
Yes, YOLO shouldn't be explained.

2023-07-10 09:35 UTC, juanjoman commented on README.md
> +5. **Flexibility:** Application's needs grow constantly, and so does AI applications. That's why we are adopting a
Awesome! I was also missing a "catchier" pitch :P

2023-07-11 17:05 UTC, javiertoledo requested changes
Great work @juanjoman! I've added many suggestions to edit and reorganize the content, but it's a good starting point. I think we should review the pending comments and merge this PR, we can keep editing in future PRs.

2023-07-11 17:05 UTC, javiertoledo commented on README.md
> +The eLLMental project raises from the necessity of developers to have a single framework that joins flexibility,
```suggestion
The eLLMental project was born out of the necessity for developers to have a single toolset that combines flexibility,
```

2023-07-11 17:05 UTC, javiertoledo commented on README.md
> +efficiency, and productivity while building the different blocks of an AI application. During this time, we've seen different
```suggestion
efficiency, and productivity while building AI-driven applications. As a team specializing in AI product development,
```

2023-07-11 17:05 UTC, javiertoledo commented on README.md
> +challenges that motivated us to start building this project:
```suggestion
we've started to find recurrent challenges that motivated us to start building this project:
```

2023-07-11 17:05 UTC, javiertoledo commented on README.md
> +   applications.
```suggestion
1. **Lack of Robust Tools and Libraries:** As the field is relatively new, there's a shortage of high-quality production-ready tools that help developers to iterate quickly at a certain scale.
2. **MLOps management:** There's no "single click" MLOps solutions that let developers start working on their applications in a short period of time without investing a significant amount of time.
3. **Security**: Ensuring minimal security standards of the underlying infrastructure, including network security, firewall configurations, and container security, is a major challenge.
4. **Privacy:** Sometimes it's unclear how privacy is handled when using models that are behind an API provided by a startup.
5. **Dependency to the Python stack:** Most existing tools were designed by and for data scientists that use Python as their default go-to programming language, but most production apps, especially in enterprise, use JVM or .Net based stacks. This not only have an implication on the language used, but also on tooling and configuration management.
```

2023-07-11 17:05 UTC, javiertoledo commented on README.md
> +After that, you can run `./gradlew :<your_service>:run` to serve your API.
Let's delete this from here and put a direct link to the corresponding docusaurus section. That way we avoid maintaining duplicate content and we keep the README simple

2023-07-11 17:05 UTC, javiertoledo commented on README.md
> +> Remember to label the issue with an "enhancement" tag
Let's move this to a document called CONTRIBUTING.md in the project's root and add a direct link here to that document. There's a reference document that we can copy in the Booster's repo with A LOT of extra info that could be useful here: https://github.com/boostercloud/booster/blob/main/CONTRIBUTING.md

2023-07-11 17:05 UTC, javiertoledo commented on README.md
> +in [this article](https://timreview.ca/article/691).
We're finally going with the Apache 2.0 license:

```suggestion
The eLLMental project is licensed under the terms of the Apache License, Version 2.0. See the [LICENSE][LICENSE] file for details.
```

2023-07-11 17:05 UTC, javiertoledo commented on README.md
> +eLLMental is a project by [The Agile Monkeys](https://www.theagilemonkeys.com/).
```suggestion
eLLMental is n open-source initiative by [The Agile Monkeys](https://www.theagilemonkeys.com/).
```

2023-07-11 17:05 UTC, javiertoledo commented on website/docs/01_introduction.md
> +   applications.
```suggestion
The eLLMental project was born out of the necessity for developers to have a single toolset that combines flexibility,
efficiency, and productivity while building AI-driven applications. As a team specializing in AI product development,
we've started to find recurrent challenges that motivated us to start building this project:

1. **Lack of Robust Tools and Libraries:** As the field is relatively new, there's a shortage of high-quality production-ready tools that help developers to iterate quickly at a certain scale.
2. **MLOps management:** There's no "single click" MLOps solutions that let developers start working on their applications in a short period of time without investing a significant amount of time.
3. **Security**: Ensuring minimal security standards of the underlying infrastructure, including network security, firewall configurations, and container security, is a major challenge.
4. **Privacy:** Sometimes it's unclear how privacy is handled when using models that are behind an API provided by a startup.
5. **Dependency to the Python stack:** Most existing tools were designed by and for data scientists that use Python as their default go-to programming language, but most production apps, especially in enterprise, use JVM or .Net based stacks. This not only have an implication on the language used, but also on tooling and configuration management.
```

2023-07-11 17:05 UTC, javiertoledo commented on website/docs/03_deployments.md
> +<Andre's PR here>
Do we need to merge @mnlx's PR before merging this one?

2023-07-11 17:05 UTC, javiertoledo commented on website/docs/04_contributing.md
> +eLLMental is a project by [The Agile Monkeys](https://www.theagilemonkeys.com/).
Maybe we can render the CONTRIBUTING.md document here somehow to avoid duplicating content?

2023-07-12 09:52 UTC, juanjoman commented on website/docs/03_deployments.md
> +<Andre's PR here>
Or he can merge his after this one is merged @javiertoledo

2023-07-12 10:21 UTC, juanjoman commented on .github/workflows/wf_publish-docs.yml
> +          curl -o CONTRIBUTING.md https://raw.githubusercontent.com/theam/eLLMental/main/CONTRIBUTING.md
Disclaimer: This will only work when the repo is public

This workaround is done because when we publish the workdir is `website` dir, so we can't access the contributing file in root

2023-07-12 10:23 UTC, juanjoman commented on .github/workflows/wf_publish-docs.yml
> +  pull_request:
We need to change before merging, I use this to test in the PR

2023-07-12 10:47 UTC, javiertoledo approved these changes
@juanjoman this is a great v1 for the docs, README and CONTRIBUTING, if there are no other pending conversations, I'd merge it and plan further changes in future PRs

2023-07-12 19:46 UTC, merged